name = "gatsby-typescript-template"
type = "webpack"
workers_dev = true
zone_id = "2c4e077b90608d343e361b4dca6335f0"
account_id = "bf7a009ee5034e5743a0e77aacffbe0a"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.beta]
name = "gatsby-typescript-template-beta"

[env.prod]
name = "gatsby-typescript-template-prod"
